### Get Message
GET http://localhost:3003/message

### Create Message
POST https://sz-be.vercel.app/message
Content-Type: application/json

{
    "text": "tolong buatkan artikel singkat 1 paragraf mengenai kenakalan remaja"
}

